//SignIn
export const SIGN_IN_EMAIL_CHANGED = 'SIGN_IN_EMAIL_CHANGED';
export const SIGN_IN_PASSWORD_CHANGED = 'SIGN_IN_PASSWORD_CHANGED';
export const SIGN_IN_LOGIN_USER_SUCCESS = 'SIGN_IN_LOGIN_USER_SUCCESS';
export const SIGN_IN_START_LOADER = 'SIGN_IN_START_LOADER';
export const SIGN_IN_SET_ERREUR = 'SIGN_IN_SET_ERREUR';
export const SIGN_IN_INITIAL_STATE = 'SIGN_IN_INITIAL_STATE';
export const ON_SIGN_OUT = 'ON_SIGN_OUT';
//AppLoading
export const SET_USER_IN_REDUCER = 'SET_USER_IN_REDUCER';
export const IS_CONNECTED_APP = 'IS_CONNECTED_APP';
export const IS_REFRESH_CONNECTED_APP = 'IS_REFRESH_CONNECTED_APP';
//Home
export const HOME_START_REFRESHING = 'HOME_START_REFRESHING';
export const HOME_GET_LIST_CARS_SUCCESS = 'HOME_GET_LIST_CARS_SUCCESS';
//Map
export const MAP_GET_LIST_CORRDINATE_CARS_SUCCESS = 'MAP_GET_LIST_CORRDINATE_CARS_SUCCESS';
